---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: usergroupmgmtcentos8
    image: registry.gitlab.com/dvonessen/docker-ansible-systemd-nonroot-centos:8
    command: /usr/lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: usergroupmgmtdebian10
    image: registry.gitlab.com/dvonessen/docker-ansible-systemd-nonroot-debian:10
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
